All readme.md files have been translated
4xmen/Get-Github-Achievements pull request #51
Opened 2023-07-07 08:36 UTC by emreyunusbas

Necessary address updates were made

2023-07-07 09:48 UTC, YasinDehfuli approved these changes

2023-07-07 11:01 UTC, YasinDehfuli requested changes
hi, @emreyunusbas, because of some conflicts i cant accept and merge your changes. please fix the reviewed comments.  after conflict bug fix i can accept your Turkey translate & add you to our contributers

2023-07-07 19:48 UTC, emreyunusbas commented on assets/steps-tr/README.yolo-tr.md
I think I have corrected the existing conflicts, you can check and come back or add it directly if it is correct. and I have corrected the translations in the course and other files in yolo

2023-07-08 07:01 UTC, YasinDehfuli commented on assets/steps-tr/README.yolo-tr.md
![image](https://github.com/4xmen/Get-Github-Achievements/assets/110921275/a854e42b-fbe3-4a22-aee5-7841dc59cf63)

as you can see you need to remove turkish button in README.md to fix the conflict. 
i presure your job, and i want to accept it but we need to fix conflict in README.md

2023-07-08 07:17 UTC, YasinDehfuli commented
Please Remove main README.md file i will add button on turkey

2023-07-08 07:43 UTC, closed without merging