Add french language + Fixing
4xmen/Get-Github-Achievements pull request #9
Opened 2023-05-12 17:49 UTC by amirroox

با سلام و عرض خسته نباشید . زبان فرانسوی به عنوان Branch جدید به پروژه اضافه شد . (پوشه steps ایجاد شده و تمامی فایل ها ترجمه شده ان) علاوه بر تغییرات زبانی چنیدن مشکل اعم از لینک دهی ها بهبود یافتند و همچنین عکس پین Galaxy Brain  اضافه شد .

2023-05-12 17:57 UTC, amirroox commented
بهبود لینک دهی :
آدرس های : 
https://github.com/4xmen/Get-Github-Achievements/blob/main/.......
به آدرس های بدون این قسمت تبدیل شده اند (برای دسترسی مستقیم از هر فورک )

2023-05-13 07:37 UTC, YasinDehfuli requested changes
You change the links to other languages pages by changing it.
i show you a sample to change main translated languages 

https://github.com/4xmen/Get-Github-Achievements/blob/master/YOUR-NEW-README.md-HERE

add your main new language translate must be in YOUR-NEW-README.md-HERE;

Add README.fr.md in there

2023-05-13 07:37 UTC, YasinDehfuli commented on README.de.md
> +[![en](https://img.shields.io/badge/Lang-English-blue.svg)](README.md)
You shouldn't change the link, now the link is broken

2023-05-13 07:37 UTC, YasinDehfuli commented on README.de.md
> +[![fa](https://img.shields.io/badge/Lang-Persian-green.svg)](README.fa.md)
you broke the link https://github.com/4xmen/Get-Github-Achievements/blob/master/README.fa.md is true link

2023-05-13 07:37 UTC, YasinDehfuli commented on README.de.md
> +[![de](https://img.shields.io/badge/Lang-Deutsch-yellow.svg)](README.de.md)
you broke the link here

2023-05-13 07:37 UTC, YasinDehfuli commented on README.de.md
> +[![fr](https://img.shields.io/badge/Lang-french-orange.svg)](README.fr.md)
you broke the link here

2023-05-13 07:37 UTC, YasinDehfuli commented on README.fa.md
> +[![en](https://img.shields.io/badge/Lang-English-blue.svg)](README.md)
don't change true parts that work successfully, now you broke the link

2023-05-13 07:37 UTC, YasinDehfuli commented on README.fa.md
> +[![fa](https://img.shields.io/badge/Lang-Persian-green.svg)](README.fa.md)
the link didn't work like this

2023-05-13 07:37 UTC, YasinDehfuli commented on README.fr.md
> +[![en](https://img.shields.io/badge/Lang-English-blue.svg)](README.md)
please code like other samples, don't change it, links didn't work like this

2023-05-13 07:37 UTC, YasinDehfuli commented on README.fr.md
> +[![fr](https://img.shields.io/badge/Lang-french-orange.svg)](README.fr.md)
please change the changes, like other pages sample, your changes on links broken the link to other languages pages , fix it and pull again

2023-05-13 07:39 UTC, YasinDehfuli commented
با سلام تغییر در لینک باعث میشود دسترسی به بخش ها مسدود شود بر طبق نحوه کار README لطفا لینک هارا به حالت اولیه تغییر دهید و از همان روش برای لینک کردن استفاده کنید که استفاده شده بود. با تشکر از زحمات شما

2023-05-13 12:33 UTC, amirroox commented
سلامی دوباره ، لینک ها به حالت عادی برگشتند (البته من تست کردم ، مشکلی از نظر لینک دهی نداشت و به همین صورت هم به صفحات جدید منتقل میشد) در هر صورت لینک های گفته شده به حالت عادی برگشتند

2023-05-13 17:37 UTC, YasinDehfuli approved these changes

2023-05-13 17:37 UTC, YasinDehfuli commented on README.md
> +[![en](https://img.shields.io/badge/Lang-English-blue.svg)](https://github.com/4xmen/Get-Github-Achievements/blob/master/README.md)
تشکر از فیکس بخش ها - لینک قبلی در صورتی که در گیت هاب پوش میشد فعال نمیبود. قبلا امتحان شده بود این روش - تشکر از تغییرات شما

2023-05-13 17:40 UTC, YasinDehfuli commented on README.md
> +[![en](https://img.shields.io/badge/Lang-English-blue.svg)](https://github.com/4xmen/Get-Github-Achievements/blob/master/README.md)
با تشکر از شما دوست عزیز @amirroox  
لطفا در صورتی که بخش main را ساخته اید بخش, steps هم بسازیدو آموزش مرحله به مرحله هم ترجمه کنید برای سهولت کاراستفاده کنندگان مجموعه. 

در صورتی که مشکل داشتید. میتوانم سمپل اولیه را بسازم و تنها بخش ترجمه به فرانسوی را به شما بسپارم. 

با تشکر @YasinDehfuli

2023-05-13 17:41 UTC, merged

2023-05-13 17:47 UTC, amirroox commented on README.md
> +[![en](https://img.shields.io/badge/Lang-English-blue.svg)](https://github.com/4xmen/Get-Github-Achievements/blob/master/README.md)
سلام دوست من ، بخش steps ها هم ترجمه شده اند (همین برنچی که مرج کردید) 
پوشه steps-fr در بخش assets ساخته شده

2023-05-13 17:58 UTC, YasinDehfuli commented
دوست عزیز @amirroox 
خوشحالیم از اینکه شاهد این هستیم که پین Pull Shark را دریافت کردید و این اتفاق در کنار تیم 4xmen بوده.
از تمامی زحمات شما سپاسگذاریم.

از طرف تیم [4xmen](https://github.com/4xmen)

2023-05-13 18:09 UTC, amirroox commented
منم خوشحال شدم تا تونستم قسمتی از این پروژه رو تکمیل کنم 
و برای اینکه کاربران ترغیب بشن برای دریافت پین ها و همچنین کمک به بقیه پروژه ها  با این اکانت درخواست دادم  
موفق و پیروز باشید